backend/app/urls.py
from rest_framework import routers
from django.urls import path, include

from .views.views import *
app_name='app'


router = routers.DefaultRouter()


urlpatterns = []


router.register(r'gros', GrosViewSet, basename='gros')
router.register(r'article', ArticleViewSet, basename='article')
router.register(r'position', PositionViewSet, basename='position')
router.register(r'bulletinsescort', BulletinsEscortViewSet, basename='bulletinsescort')
router.register(r'tc', TcViewSet, basename='tc')
router.register(r'sousarticle', SousArticleViewSet, basename='sousarticle')
router.register(r'visite', VisiteViewSet, basename='visite')
router.register(r'visiteitem', VisiteItemViewSet, basename='visiteitem')
router.register(r'scelle', ScelleViewSet, basename='scelle')
urlpatterns += router.urls

backend/groupage/urls.py
from rest_framework import routers
from .views import *
from django.urls import path, include


app_name='groupage'


router = routers.DefaultRouter()


urlpatterns = [
  
]


router.register(r'visitegroupage', VisiteGroupageViewSet, basename='visitegroupage')
router.register(r'positiongroupage', PositionGroupageViewSet, basename='positiongroupage')
urlpatterns += router.urls

backend/src/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views.views import *
from billing.views import * 
from groupage.views import * 
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/auth/', include('authentication.urls')),
    path('api/container/', include('app.urls')),
    path('api/bareme/', include('bareme.urls')),
    path('api/billing/', include('billing.urls')),
    path('api/reposrting/', include('reporting.urls')),
    path('api/reference/', include('reference.urls')),
    path('api/groupage/', include('groupage.urls'))
]

backend/groupage/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.db.models import Max, Sum
from django.db.models.signals import post_delete, post_save
from datetime import date, datetime
from src.methods import *
from app.models import *

def getNextNumber(prefix,model):
    all = model.objects.filter(date_creation__year = date.today().year).order_by("numero")
    last = all.last()

    if not last or (last.date_creation.year != date.today().year):
        return prefix+'000001'
    else: 
        max = 0
        for record in all: 
            if int(record.numero.split(prefix)[-1]) > max : 
                max = int(record.numero.split(prefix)[-1]) 

        new_int = max + 1
        new_no = prefix + format(new_int, '06d')

    return new_no 


def getNumeroVisiteGroupage():
    return getNextNumber('V/GROUPAGE',VisiteGroupage)

def getNumeroFacture():
    pass

class VisiteGroupage(models.Model):
    TYPES_VISITE = [
        ('Visite douane', 'Visite douane'),
        ('Visite D41', 'Visite D41'),
    ]
    visite = models.CharField(max_length=50, blank=True, null=True, unique=True)
    numero = models.CharField(max_length=17, default=getNumeroVisiteGroupage)
    date_creation = models.DateField(auto_now_add=True)
    date_visite = models.DateField(auto_now=False, auto_now_add=False, default=datetime.now)
    gros = models.ForeignKey("app.Gros", on_delete=models.PROTECT)
    article = models.ForeignKey("app.Article", on_delete=models.CASCADE, blank=True, null=True)
    sous_article = models.ForeignKey("app.SousArticle", on_delete=models.CASCADE, blank=True, null=True)
    type_visite = models.CharField(max_length=15, choices=TYPES_VISITE)
    transitaire = models.ForeignKey("reference.Transitaire", on_delete=models.PROTECT)
    badge = models.CharField(max_length=50)
 
    class Meta:
        ordering = ["id"]
        verbose_name_plural = "viites"
        
    def clean(self):
            records_count = VisiteGroupage.objects.filter(date_creation__year = date.today().year,numero = self.numero).count()
            if records_count > 0: 
                raise ValidationError({"numero":"Visite aleady exist."})

    def __str__(self):
        return self.numero

    def save(self, *args, **kwargs):
        self.visite = self.numero + " / " + str(self.date_visite.year)
            
        super(VisiteGroupage, self).save(*args, **kwargs)

class PositionGroupage(models.Model): 
    sous_article = models.ForeignKey("app.SousArticle", on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    box = models.ForeignKey("reference.Box", on_delete=models.CASCADE)
    
    def update_sous_article_position(self): 
        self.sous_article.box = self.box 
        self.sous_article.save()
    
    def __str__(self):
        return str(self.box) + " " + str(self.date) 
    
def post_save_position_groupage(sender, instance,**kwargs): 
        instance.update_sous_article_position()

post_save.connect(post_save_position_groupage, sender = PositionGroupage)

backend/groupage/forms.py
from app.models import * 
from groupage.models import *
from django import forms
from django.forms import ModelForm 
from .models import *
from django.core.exceptions import NON_FIELD_ERRORS
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User 
import datetime
from reference.models import Client, Transitaire

class VisiteGroupageForm(ModelForm):
    class Meta:
        model = VisiteGroupage
        fields = ['gros','article','sous_article','numero','type_visite','date_visite','transitaire','badge' ]
        widgets = {
            'gros' : forms.Select(attrs={'class':'form-control shadow-none'}), 
            'article' : forms.Select(attrs={'class':'form-control shadow-none'}), 
            'sous_article' : forms.Select(attrs={'class':'form-control shadow-none'}), 
            'numero' : forms.TextInput(attrs={'class':'form-control shadow-none disable', 'readonly':True}),
            'type_visite' : forms.Select(attrs={'class':'form-control shadow-none'}), 
            'date_visite' : forms.DateInput(attrs={'type':'date' ,'class':'form-control shadow-none','min': '2018-01-01'}),
            'transitaire' : forms.Select(attrs={'class':'form-control shadow-none'}), 
            'badge' : forms.TextInput(attrs={'class':'form-control shadow-none disable'}),
            'description' : forms.TextInput(attrs={'class':'form-control shadow-none disable'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['article'].queryset = Article.objects.none()
        self.fields['sous_article'].queryset = SousArticle.objects.none()

backend/groupage/views.py
from rest_framework.response import Response
from rest_framework import viewsets,filters,status
from rest_framework.decorators import action
from rest_framework.pagination import PageNumberPagination
from .models import *
from .filters import *
from django_filters.rest_framework import DjangoFilterBackend
from rest_flex_fields import is_expanded
from app.serializers import *
from bareme.serializers import *
from reference.serializers import *
from billing.serializers import *
from reporting.serializers import *


class CustomPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = 10000


class VisiteGroupageViewSet(viewsets.ModelViewSet):
    queryset = VisiteGroupage.objects.all()
    filter_backends = [DjangoFilterBackend,filters.OrderingFilter]
    serializer_class = VisiteGroupageSerializer
    pagination_class = CustomPagination
    ordering_fields = '__all__'
    filterset_class= VisiteGroupageFilter


    def get_queryset(self):
        queryset = VisiteGroupage.objects.all()
        if is_expanded(self.request, 'gros'):
            queryset = queryset.prefetch_related('gros')
        if is_expanded(self.request, 'article'):
            queryset = queryset.prefetch_related('article')
        if is_expanded(self.request, 'sous_article'):
            queryset = queryset.prefetch_related('sous_article')
        if is_expanded(self.request, 'transitaire'):
            queryset = queryset.prefetch_related('transitaire')
        return queryset


    def list(self, request, *args, **kwargs):
        # Check if the 'all' parameter is present in the request query parameters
        if request.query_params.get('all', False):
            # If 'all' is present, return all records without pagination
            queryset = self.filter_queryset(self.get_queryset())
            serializer = self.get_serializer(queryset, many=True)
            return Response(serializer.data)
        # If 'all' is not present, proceed with pagination as usual
        return super().list(request, *args, **kwargs)


    @action(detail=False, methods=['post'])
    def bulk_delete(self, request, *args, **kwargs):
        ids = request.data.get('ids', [])
        if not ids:
           return Response({'detail': 'No IDs provided for deletion.'}, status=status.HTTP_400_BAD_REQUEST)
        try:
            queryset = self.filter_queryset(self.get_queryset())
            deleted, _ = queryset.filter(pk__in=ids).delete()
            if deleted > 0:
               return Response({'detail': f'Successfully deleted objects with ids: {ids} .'}, status=status.HTTP_204_NO_CONTENT)
            else:
               return Response({'detail': 'No objects found for deletion.'}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
           return Response({'detail': f'Error during deletion: {str(e)}'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)


class PositionGroupageViewSet(viewsets.ModelViewSet):
    queryset = PositionGroupage.objects.all()
    filter_backends = [DjangoFilterBackend,filters.OrderingFilter]
    serializer_class = PositionGroupageSerializer
    pagination_class = CustomPagination
    ordering_fields = '__all__'
    filterset_class= PositionGroupageFilter


    def get_queryset(self):
        queryset = PositionGroupage.objects.all()
        if is_expanded(self.request, 'sous_article'):
            queryset = queryset.prefetch_related('sous_article')
        if is_expanded(self.request, 'box'):
            queryset = queryset.prefetch_related('box')
        return queryset


    def list(self, request, *args, **kwargs):
        # Check if the 'all' parameter is present in the request query parameters
        if request.query_params.get('all', False):
            # If 'all' is present, return all records without pagination
            queryset = self.filter_queryset(self.get_queryset())
            serializer = self.get_serializer(queryset, many=True)
            return Response(serializer.data)
        # If 'all' is not present, proceed with pagination as usual
        return super().list(request, *args, **kwargs)


    @action(detail=False, methods=['post'])
    def bulk_delete(self, request, *args, **kwargs):
        ids = request.data.get('ids', [])
        if not ids:
           return Response({'detail': 'No IDs provided for deletion.'}, status=status.HTTP_400_BAD_REQUEST)
        try:
            queryset = self.filter_queryset(self.get_queryset())
            deleted, _ = queryset.filter(pk__in=ids).delete()
            if deleted > 0:
               return Response({'detail': f'Successfully deleted objects with ids: {ids} .'}, status=status.HTTP_204_NO_CONTENT)
            else:
               return Response({'detail': 'No objects found for deletion.'}, status=status.HTTP_404_NOT_FOUND)
        except Exception as e:
           return Response({'detail': f'Error during deletion: {str(e)}'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

backend/groupage/templates/groupage/pages/groupage.html
{% extends 'app/components/base.html' %}

{% block content %}

{% include 'app/components/navbar.html' with title='Groupage' %}
{% include 'app/components/messages.html' %}

<div class="row mb-2">
    <div class="col-md-4 mt-4 mt-lg-0">
        {% include 'app/components/search.html' with form=search_form%}
    </div> 
 
</div>


<div class="card">
    <div class="card-body p-2 p-lg-3 pb-0">
 
        <!-- Add gros modal trigger -->

        {% include 'app/components/messages.html' %}
        
        <div class="table-responsive mb-2">
            <table class="table table-hover table-borderless table-centered table-nowrap mb-0 rounded">
                <thead class="thead-light border-0">
                    <tr class="mb-4">
                        <th class="rounded-start">Numero</th>
                        <th >Régime</th>
                        <th >Accosstage</th>
                        <th >Navire</th>
                        <th >Armateur</th>
                        <th class="rounded-end">Consignataire</th>
                       
                    </tr>
                </thead>
                <tbody id="gross">
                    <!-- Item -->
                  {% if data|length > 0 %}
                  {% for item in data %}
                  <tr id="{{ item.id }}">
                    <td class="rounded-start">
                        <a class="btn btn-sm btn-gray-100 shadow-none" type="button"  href="{% url 'groupage_gros_details' item.id %}"> 
                          {{ item.gros }}
                        </a>              
                    </td>
                    <td class="border-0 align-middle">
                      {% if item.regime__designation == 'D1' %}
                          <span class="badge bg-success p-2">{{ item.regime__designation }}</span> 
                      {% elif item.regime__designation == 'OT'%}
                          <span class="badge bg-info p-2">{{ item.regime__designation }}</span> 
                      {% elif item.regime__designation == 'D15'%}
                          <span class="badge bg-secondary p-2">{{ item.regime__designation }}</span>
                      {% else %} 
                          <span class="badge bg-light p-2">{{ item.regime__designation }}</span>
                      {% endif %} 
                    </td>
                    <td class="border-0 align-middle">
                      {{ item.accostage|date:"l, d-m-Y" }}  
                    </td>
                    <td class="border-0 align-middle">
                      {{ item.navire__nom }}
                    </td>
                    <td class="border-0 align-middle align-middle">
                      {{ item.armateur__raison_sociale }}
                    </td>
                    <td class="rounded-end align-middle">
                      {{ item.consignataire__raison_sociale }}
                    </td>
                  </tr>
                  {% endfor %}
                  {% endif %}             
        
        
                </tbody>
            </table>
        </div>
        {% include 'app/components/pagination.html' %}

        

    </div>
</div>


<script>
    window.onload = (event) => {
        printitems('nav16');
    };
</script>
{% endblock content %}

backend/groupage/templates/groupage/pages/groupage_gros_details.html
{% extends 'app/components/base.html' %}
{% load slice %}
{% block content %}

{% include 'app/components/navbar.html' with title=gros.gros %}
{% include 'app/components/messages.html' %}

<div class="card bg-gray-200 mt-4 mb-0 mb-lg-3">
    <div class="card-body p-3">
        <div class="row">
            <div class="col-12 col-lg-6">

                <div class="mb-2 d-block d-lg-none">
                    <b>Gros</b>  &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ gros.gros }}</span>
                </div>

                <div class="mb-2">
                    <b>Articles</b>  &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ tcs_count }}</span>
                </div>
                <div class="mb-2">
                    <b>Accostage</b>  &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ gros.accostage|date:"D, d M Y" }}</span>
                </div>
                <div class="mb-2">
                    <b>Navire</b> &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ gros.navire }}</span>
                </div>


            </div> 

            <div class="col-12 col-lg-6">

                <div class="mb-2">
                    <b>Armateur</b> &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ gros.armateur }}</span>
                </div>
                <div class="mb-2">
                    <b>Consignataire</b> &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ gros.consignataire }}</span>
                </div>
                <div >
                    <b>Régime</b> &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ gros.regime }}</span>
                </div>

            </div>
        </div>
        </div>
    </div>
                
<div class="row mb-2">
    <div class="col-md-4 mt-4 mt-lg-0">
        {% include 'app/components/search.html' %}
    </div> 
    <div class="col-md-2">
        <a class="btn btn-secondary shadow-none shadow-none w-100" onclick="fillTransitaires()" data-bs-toggle="modal" href="#update_modal" role="button" >
            <svg xmlns="http://www.w3.org/2000/svg" id="Outline" viewBox="0 0 24 24" width="16" height="16"><path d="M22.95,9.6a1,1,0,0,0-1.414,0L10.644,20.539a5,5,0,1,1-7.072-7.071L14.121,2.876a3,3,0,0,1,4.243,4.242L7.815,17.71a1.022,1.022,0,0,1-1.414,0,1,1,0,0,1,0-1.414l9.392-9.435a1,1,0,0,0-1.414-1.414L4.987,14.882a3,3,0,0,0,0,4.243,3.073,3.073,0,0,0,4.243,0L19.778,8.532a5,5,0,0,0-7.071-7.07L2.158,12.054a7,7,0,0,0,9.9,9.9L22.95,11.018A1,1,0,0,0,22.95,9.6Z"/></svg>
        </a>     
    </div>
</div>


<div class="modal fade" id="update_modal" aria-hidden="true" aria-labelledby="..." tabindex="-1"  >
    <div class="modal-dialog modal-md modal-dialog-centered">
      <div class="modal-content bg-gray-200">
        
          <div class="modal-body">
            <span class="badge bg-white text-primary p-2 mb-3">EDI</span>

            <form method="post" action="{% url 'chargement_sous_articles' gros.id %}"  enctype="multipart/form-data" >
                {% csrf_token %} 
                <div class='row mb-3'>
                    <div class="col-12 col-lg-6">
                        <label for="formFileSm" class="form-label">Le fichier conta.txt</label>
                        <input class="form-control border-0 shadow-none"  id="formFileSm" type="file" name="conta" >
                    </div>

                    <div class="col-12 col-lg-6 mt-4 mt-lg-0">
                        <label for="formFileSm" class="form-label">Le fichier lignes.txt</label>
                        <input class="form-control border-0 shadow-none"  id="formFileSm" type="file" name="ligne" >
                    </div>
                </div>
                
            <div class="mt-2 float-end"> 
                <a  class="btn btn-white  mr-2" data-bs-dismiss="modal">Annuler</a>
                <button type="submit" class="btn btn-primary">Sumettre</button>
            </div>

  
          </form>
      </div>
    </div>
  </div>
</div>

    <div class="card">
        <div class="card-body p-2 p-lg-3 pb-0">
            <div class="table-responsive mb-2">
                <table class="table table-hover table-borderless table-centered table-nowrap mb-0 rounded">
                    <thead class="thead-light border-0">
                        <tr>
                            <th class="rounded-start">Article</th>
                            <th class="rounded-start">Depotage</th>
                            <th>Bl</th>
                            <th>Client</th>
                            <th class="rounded-end">Désignation</th>
                        </tr>
                    </thead>
                    <tbody>       
                        {% for item in articles %} 
                            {% if item.groupage %}
                                <tr>
                                    {% if item.depote %}
                                        <td class="rounded-start"><a  type="button" class="btn btn-sm btn-success shadow-none" href="{% url 'groupage_article_details' item.id %}" role="button">{{ item.numero }}</a> </td>
                                    {% else %}
                                        <td class="rounded-start"><a  type="button" class="btn btn-sm btn-gray-200 shadow-none" href="{% url 'groupage_article_details' item.id %}" role="button">{{ item.numero }}</a> </td>
                                    {% endif %}
                                    {% if item.depote %}
                                        <td class="align-middle"><span class="badge bg-success p-2">Depoté</span> </td>
                                    {% else %}
                                        <td class="align-middle"><span class="badge bg-gray-200 text-primary p-2">None depoté</span></td>
                                    {% endif %}
                                    <td class="align-middle">{{ item.bl }}</td>
                                    <td class="align-middle">{{ item.client.raison_sociale }}</td>
                                    <td class="align-middle rounded-end">{{ item.designation }}</td>
                                </tr>
                            {% else %}
                                <tr>
                                    <td class="rounded-start"><a  type="button" class="btn btn-sm btn-gray-100 shadow-none" href="{% url 'facturation_detials' item.id %}" role="button">{{ item.numero }}</a> </td>
                                    <td class="align-middle">{{ item.bl }}</td>
                                    <td class="align-middle">{{ item.client }}</td>
                                    <td class=" align-middle rounded-end" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ item.designation}}">{{ item.designation|sliceText }}</td>
                                </tr>
                            {% endif %}                  
                        {% endfor %}   
                    </tbody>
                </table> 
            </div>
                {% include "app/components/pagination.html" with data=articles %}
           
       </div>
    </div>





<script>
    window.onload = (event) => {
        printitems('nav16');
    };
</script>
{% endblock content %}

backend/groupage/templates/groupage/pages/visite_groupage.html
{% extends 'app/components/base.html' %}

{% block content %}

{% include 'app/components/navbar.html' with title='Visite Groupage' %}



<div class="row mt-4 mt-lg-0">

    <div class="col-12 col-lg-4 ">
        {% include 'app/components/search.html' with form=form%}
    </div>

    <div class="col-12 col-lg-2 offset-lg-6">
        <a type="link" class="btn btn btn-secondary shadow-none float-end w-100" data-bs-toggle="modal" href="#modal-visite">
            + Visite
        </a>   
    </div>

</div>

<div class='card border-0 mt-4 mt-lg-2'>
    <div class="body p-2 p-lg-3 pb-0">

        {% include 'groupage/components/visite_groupage_table.html' with data=records %}
        {% include "app/components/pagination.html" with data=records %}

    </div>
</div>

{% include 'groupage/components/model_visite_groupage.html' %}


{% include 'app/components/custom_add.html' with form=form_transitaire form_id='transitaire_form_id' model_id='transitaire_model_id' form_title='+ Transitaire'  %}


<script>

    window.onload = (event) => {
        printitems('nav17');
    };

document.getElementById("id_article").onchange = function() {myFunction()};

function myFunction() {
    let articles = document.getElementById("id_article");
    let selected_article = articles.options[articles.selectedIndex].id;
   
}

$("#transitaire_form_id").submit(function(e){
       var select_field = $('#id_transitaire');
       form = $("#transitaire_form_id");
       can_add_new(e, select_field, form,"{% url 'post_transitaire' %}");
   }) ;

var now = new Date();

var day = ("0" + now.getDate()).slice(-2);
var month = ("0" + (now.getMonth() + 1)).slice(-2);

var today = now.getFullYear()+"-"+(month)+"-"+(day) ;

$('#id_date_visite').val(today);

function close_model(model_id) {
  var myModalEl = model_id
  var modal = bootstrap.Modal.getInstance(myModalEl)
  modal.hide();
}

function can_add_new(e, select_field, form, api) {
    e.preventDefault();
    var serializedData = form.serialize();
    $.ajax({
        type: 'POST',
        url: api,
        data: serializedData,
        success: function (response) {
            data = JSON.parse(response.instance)[0].fields;
            id = JSON.parse(response.instance)[0].pk;
            console.log(data);
            select_field.append(`<option value="`+ id +`"> `+ data.raison_sociale +` </option>`);     
            select_field.val(id);
            close_model("transitaire_model_id");
        },
        error: function (response) {
            // alert the error if any error occured
            console.log(response.responseText);
        }
    })
}

let select_gros =  document.getElementById("id_gros");
select_gros.addEventListener('change', function() {
    get_articles(select_gros.value);
});

let select_article =  document.getElementById("id_article");
select_article.addEventListener('change', function() {
    get_sous_articles(select_article.value);
});

function get_articles(selected_gros_id){
    let select_article = document.getElementById('id_article');
    $.ajax({
            type: 'GET',
            url: "{% url 'articles_groupage_by_gros_visite' %}",
            data: {
                "gros_id": selected_gros_id,
            },
            success: function (response) { 
                select_article.innerHTML = "";
                console.log(response.data);
                if(response.data.length > 0 ){
                    console.log(response.data)
                    var option = document.createElement("option");
                        option.text = "---------";
                        option.value = "";
                        select_article.add(option);

                    response.data.forEach(item => {
                        var option = document.createElement("option");
                        option.text = item.numero;
                        option.value = item.id;
                        select_article.add(option);
                    }
                )
                } 
              
            },
            error: function (response) {
                alert(response["responseJSON"]["error"]);
            }
        })  
}

document.getElementById("id_sous_article").onchange = function() {set_volume()};

var data;
function set_volume(volume){
    let sous_articles = document.getElementById("id_sous_article");
    let selected_sous_article = sous_articles.options[sous_articles.selectedIndex].innerHTML;
    
    data.forEach(item => {


        if (item.numero == selected_sous_article){
            
            if(item.volume == null){
                document.getElementById('id_volume').value = 0.00;
            }else{
                document.getElementById('id_volume').value = item.volume;
            }
            
        } 

    });
}
function get_sous_articles(selected_article_id){
    let select_sous_article = document.getElementById('id_sous_article');
    $.ajax({
            type: 'GET',
            url: "{% url 'sous_articles_by_article_visite' %}",
            data: {
                "article_id": selected_article_id,
            },
            success: function (response) { 
                select_sous_article.innerHTML = "";
                console.log(response.data);
                data = response.data;
                if(response.data.length > 0 ){
                   
                    var option = document.createElement("option");
                        option.text = "---------";
                        option.value = "";
                        select_sous_article.add(option);

                    response.data.forEach(item => {
                        var option = document.createElement("option");
                        option.text = item.numero;
                        option.value = item.id;
                        select_sous_article.add(option);
                    }
                )
                } 
              
            },
            error: function (response) {
                alert(response["responseJSON"]["error"]);
            }
        })  
}

let form = document.getElementById('form-visite');
form.onsubmit = createVsiste;

function createVsiste(event){
    event.preventDefault();
    form = $("#form-visite");
    var serializedData = form.serialize();

    $.ajax({
            type: 'POST',
            url: "{% url 'post_visite_groupage' %}" ,
            data: serializedData,
            success: function (response) { 
                id = JSON.parse(response.instance)[0].pk;
                fields = JSON.parse(response.instance)[0].fields;
                link = "{% url 'print_visite_groupage' 5 %}"
                window.open(link.replace('5',id), '_blank');
                location.reload();
                /*console.log(fields.date_creation)
                table = document.getElementById("visite-groupage-table")
                link = "{% url 'print_visite_groupage' 5 %}"
                window.location.href = link.replace('5',id);

                var row = table.insertRow(0);

                var numero_cell = row.insertCell(0);
                var gros_cell = row.insertCell(1);
                var tc_cell = row.insertCell(2);
                var commande_cell = row.insertCell(3);
                var quantite_cell = row.insertCell(4);
                var print_cell = row.insertCell(5);
        
                link = "{% url 'print_commande' 1 2 %}"
        
                link = link.replace('1',data[i].bon_commande__id);
                link = link.replace('2',data[i].tc__id);
        
        
                numero_cell.innerHTML=  data[i].bon_commande__numero;
                date_creation_cell.innerHTML= data[i].bon_commande__date_creation;
                tc_cell.innerHTML= data[i].tc;
                commande_cell.innerHTML= data[i].type;
                quantite_cell.innerHTML= data[i].quantite;
                print_cell.innerHTML=  '<a class="btn btn-secondary btn-sm  shadow-none" tabindex="-1" target="_blank" role="button" aria-disabled="true" href="'+link+'">PRINT</a>' ; */
            },
            error: function (response) {
                console.log(response);
            }
        }) 
}
 
</script>
{% endblock content %}