backend/app/urls.py
from rest_framework import routers
from django.urls import path, include

from .views.views import *
app_name='app'


router = routers.DefaultRouter()


urlpatterns = []


router.register(r'gros', GrosViewSet, basename='gros')
router.register(r'article', ArticleViewSet, basename='article')
router.register(r'position', PositionViewSet, basename='position')
router.register(r'bulletinsescort', BulletinsEscortViewSet, basename='bulletinsescort')
router.register(r'tc', TcViewSet, basename='tc')
router.register(r'sousarticle', SousArticleViewSet, basename='sousarticle')
router.register(r'visite', VisiteViewSet, basename='visite')
router.register(r'visiteitem', VisiteItemViewSet, basename='visiteitem')
router.register(r'scelle', ScelleViewSet, basename='scelle')
urlpatterns += router.urls

backend/src/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views.views import *
from billing.views import * 
from groupage.views import * 
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/auth/', include('authentication.urls')),
    path('api/container/', include('app.urls')),
    path('api/bareme/', include('bareme.urls')),
    path('api/billing/', include('billing.urls')),
    path('api/reposrting/', include('reporting.urls')),
    path('api/reference/', include('reference.urls')),
    path('api/groupage/', include('groupage.urls'))
]

backend/billing/models.py
from logging import raiseExceptions
from multiprocessing.spawn import prepare
from xmlrpc.client import boolean
from django.contrib.admin.sites import DefaultAdminSite
from django.db import connections, models
from datetime import date, datetime
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.core.exceptions import ValidationError
from django.db.models.deletion import CASCADE
from django.db.models.expressions import OrderBy
from django.db.models.fields import DecimalField
from django.db.models.fields.related import ForeignKey
from django.db.models.fields.reverse_related import ForeignObjectRel
from django.forms import BooleanField 
from simple_history.models import HistoricalRecords
import re
from reference.models import Client 
from django.db.models import Max, Sum
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from src.methods import *
from bareme.models import *
import app.models 
from decimal import Decimal
from groupage.models import *

def total_paiements(first_date, last_date): 


    paiamants = Paiement.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']

    paiamants_complementaire = PaiementFactureComplementaire.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']

    paiements_libre = PaiementFactureLibre.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']
    
    paiements_groupage = PaiementGroupage.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']

    if paiamants is None: 
        paiamants = 0 

    if paiamants_complementaire is None: 
        paiamants_complementaire = 0 

    if paiements_libre is None: 
        paiements_libre = 0

    if paiements_groupage is None: 
        paiements_groupage = 0
        
    return round(paiamants + paiamants_complementaire + paiements_libre+paiements_groupage,0)
    

        
def getNextNumber(prefix,model):
    all = model.objects.filter(date_creation__year = date.today().year).order_by("numero")
    last = all.last()

    if not last or (last.date_creation.year != date.today().year):
        return prefix+'000001'
    else: 
        max = 0
        for record in all: 
            if int(record.numero.split(prefix)[-1]) > max : 
                max = int(record.numero.split(prefix)[-1]) 

        new_int = max + 1
        new_no = prefix + format(new_int, '06d')

    return new_no 


def getNumeroProforma():
    all = Proforma.objects.filter(date_creation__year = date.today().year).order_by("id")
    last = all.last()

    if not last or (last.date_creation.year != date.today().year):
        return 'ALG000001'
    else: 
        max = 0
        for record in all: 
            if int(record.numero.split('ALG')[-1].split('FP')[-1]) > max : 
                max = int(record.numero.split('ALG')[-1].split('FP')[-1]) 

        new_int = max + 1
        new_no = 'ALG' + format(new_int, '06d')

    return new_no 

def getNumeroFacture():
    return getNextNumber('ALG',Facture)

def getNumeroBonCommande():
    return getNextNumber('BC',BonCommande)

def getNumeroBonSortie():
    return getNextNumber('BS',BonSortie)


def getNumeroBonSortieGroupage():
    return getNextNumber('BS/G/',BonSortieGroupage)

def getNumeroFactureLibre(): 
    return getNextNumber('ALG/LIBRE',FactureLibre)

def getNumeroFactureGroupage():
    return getNextNumber('GRP',FactureGroupage)

def getNumeroProformaGroupage():
    return getNextNumber('P/GRP',ProformaGroupage)


class Proforma(models.Model):
    numero = models.CharField(max_length=9,default=getNumeroProforma)
    date_creation = models.DateField(auto_now_add=True)
    gros = models.ForeignKey("app.Gros", on_delete=models.CASCADE)
    article = models.ForeignKey("app.Article", on_delete=models.CASCADE)
    date_proforma = models.DateField(auto_now=False, auto_now_add=False)
    HT = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TVA = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TTC = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    tva = models.BooleanField(default=True, verbose_name="TVA") 
    debeur = models.BooleanField(default=False, verbose_name="DEBEUR")
    DEBEUR = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    remise = models.BooleanField(default=False)
    REMISE = models.DecimalField(max_digits=15, decimal_places=2,default=0,blank=True, null=True)
    TR = models.DecimalField(max_digits=15, decimal_places=2,blank=True, null=True)
    valide = models.BooleanField(default=False, blank=True, null=True)
    trashed = models.BooleanField(default=False, blank=True, null=True)
    entreposage = models.BooleanField(default=True, blank=True, null=True)
    
    history = HistoricalRecords()  

    def validate(self):
        self.valide = True 
        self.save()
        self.set_containers_as_billed()

    class Meta:
        ordering = ["-id"]
        verbose_name_plural = "proformas"

    def set_containers_as_billed(self): 
        for line in self.get_groupes_lines(): 
            line.tc.set_as_billed()

    def is_container_loaded(self,tc): 
        self.get_groupes_lines().filter(tc=tc).exists()

    # get all the containers that are not billed & not loaded to any proforma yet
    def get_not_loaded_containers(self): 
        return app.models.Tc.objects.filter(pk__in = [tc.id for tc in self.article.get_receved_containers().filter(billed = False) if not self.is_container_loaded(tc)])
 
    @property 
    def total_number_of_containers(self): 
        return self.groupe_set.all().aggregate(Sum('tcs'))['tcs__sum'] 

    def get_groups(self): 
        return self.groupe_set.all()

    def get_groupes_lines(self):     
        return GroupeLigne.objects.filter(groupe__in = self.get_groups())

    def get_prestations(self): 
        return self.ligneprestation_set.all()

    def get_prestations_article(self): 
        return self.ligneprestationarticle_set.all()

    def get_enterposage(self):
        return self.groupe_set.all().aggregate(Sum('enterposage'))['enterposage__sum']

    def get_ttc_in_letters(self): 
        return decimalToText(self.TTC)

    def __str__(self):
        return self.numero + " / " + str(self.date_creation.year)  

    def clean(self):
        if self.id is None :
            records_count = Proforma.objects.filter(date_creation__year = date.today().year,numero = self.numero).count()
            if records_count > 0: 
                raise ValidationError({"numero":"Proforma aleady exist."})

    def calculate_totals(self): 
        total_hors_taxes = 0   
        total_hors_taxes = get_sum_hors_taxes(self.get_prestations())
        total_hors_taxes += get_sum_hors_taxes(self.get_prestations_article())    
        remise = 0     
        if self.remise: 
            total_hors_taxes,remise = calculate_remise(total_hors_taxes, self.REMISE)
        

        if self.tva: 
            total_tva = calculate_tva(total_hors_taxes) 
        else: 
            total_tva =  0  

        self.HT  = total_hors_taxes
        self.TVA  = total_tva 
        self.TR = remise
        self.TTC = total_hors_taxes + total_tva
        if self.debeur: 
            self.TTC += self.DEBEUR
        self.save()

class Groupe(models.Model): 
    proforma = models.ForeignKey("billing.Proforma",on_delete=models.CASCADE)
    type = models.ForeignKey("reference.Type", verbose_name="Container type", on_delete=models.SET_NULL,null=True)
    dangereux = models.BooleanField()
    frigo = models.BooleanField()
    tcs = models.IntegerField(null=True, blank=True)
    enterposage = models.IntegerField(null=True, blank=True)

    @property 
    def lines(self): 
        return self.groupeligne_set.all()


    class Meta:
        verbose_name_plural = "groupes"

    def __str__(self):
        return str(self.proforma) +" | "+ str(self.type) +" | " + str(self.dangereux) +" | " + str(self.frigo) 
    
class GroupeLigne(models.Model): 
    groupe = models.ForeignKey("billing.Groupe", on_delete=models.CASCADE)
    tc = models.ForeignKey("app.Tc",on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "lignes groupe"

    def __str__(self):
        return self.groupe.type.designation+" "+self.tc.tc
    
class LignePrestation(models.Model): 
    proforma = models.ForeignKey("billing.Proforma",on_delete=models.CASCADE) 
    groupe = models.ForeignKey("billing.Groupe", on_delete=models.CASCADE, null=True, blank=True)
    rubrique = models.CharField(max_length=100)
    rubrique_object = models.ForeignKey("bareme.Rubrique", related_name="rubrique_prestation", on_delete=models.PROTECT, null=True, blank=True)
    tcs = models.IntegerField()
    quantite = models.IntegerField(blank=True , null= True)
    tarif = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    HT = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TVA = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TTC = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    code_comptable = models.CharField(max_length=30, null=True, blank=True) 
   
    def update_tva_zero(self): 
        self.TVA = 0 
        self.TTC = self.HT 
        self.save()
        
    class Meta:
        verbose_name_plural = "lignes prestation"

    def save(self, *args, **kwargs):
        if self.proforma.tva: 
            self.HT = self.tarif * self.quantite
            self.TVA = (self.HT * 19) / 100
            self.TTC = self.HT + self.TVA
        else: 
            self.HT = self.tarif * self.quantite
            self.TVA = 0
            self.TTC = self.tarif * self.quantite       
                
        super(LignePrestation, self).save(*args, **kwargs)   

    def __str__(self):

backend/app/templates/app/components/add_bulletins.html
{% load static %}
{{ form.media }}  
{% load bootstrap5 %}  


<!-- First modal dialog -->
<div class="modal fade" id="modal" aria-hidden="true" aria-labelledby="..." tabindex="-1">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content ">
        <form   method="POST" id="tonerForm" autocomplete="off">
        <div class="modal-body">
            <span class="badge bg-gray-100 text-primary p-2 mb-3"> + Bulletins d'Escort</span>

                    {% csrf_token %}
                    {% for field in form %}

                        {% if field.id_for_label == "id_charge_chargement" %}
                            <div class="row mb-3">
                                <div class="col-10">
                                <div class="form-floating">
                                    {{field}}             
                                    <label for="{{field.id_for_label}}" >{{field.label}}</label>
                                </div>
                                </div>
                               <div class="col-2 d-flex align-items-end">
                                    <a class="btn btn-primary shadow-none w-100" data-bs-toggle="modal" href="#agent_model_id" role="button" >+</a>
                                </div>
                            </div>
                            {% elif  field.id_for_label == "id_gros" %}
                  
                            <div class="row mb-3">
        
                                <div class="col-12">
                                  <div class="row">
                                  <div class="col-8">
                                    <div class="form-floating ">
      
                                        {{field}}             
                                        <label for="{{field.id_for_label}}" >{{field.label}}</label>
                                    </div>
                                  </div>
                                  
                                  <div class="col-4">
      
                                    <div class="form-floating">
                                      <input type="search" class="form-control" id="gros-search-box" oninput="searchGros()">
                                      <label for="floatingInput">Search</label>
                                    </div>
                                  </div>
                              </div>
                                </div>
        
                            </div>
      
                        {% elif field.id_for_label == "id_charge_reception" %}
                             <div class="row mb-3">
                                <div class="col-10">
                                    <div class="form-floating">
                                        {{field}}             
                                        <label for="{{field.id_for_label}}" >{{field.label}}</label>
                                    </div>
                                </div>
                               <div class="col-2 d-flex align-items-end">
                                    <a class="btn btn-primary shadow-none w-100" data-bs-toggle="modal" href="#agent_model_id" role="button" >+</a>
                                </div>
                            </div>
                        {% else %}
                            <div class="form-floating mb-3">
                                {{field}}             
                                <label for="{{field.id_for_label}}" >{{field.label}}</label>
                            </div>
                            
                        {% endif %}
                    {% endfor %}
        </div>
        <div class="modal-footer">
            <a  class="btn btn-light float-right mr-2" data-bs-dismiss="modal">Annuler</a>
            <input type="submit" class="btn btn-primary float-right" id="butt" name="SUBMIT" value="Soumettre"></a>

        </div>

        </form>
    </div>
  </div>
</div>




<script>
    var now = new Date();

    var day = ("0" + now.getDate()).slice(-2);
    var month = ("0" + (now.getMonth() + 1)).slice(-2);

    var today = now.getFullYear()+"-"+(month)+"-"+(day) ;

    $('#id_date_creation').val(today);


    function searchSelect(opetions, text){
        var options = opetions; //select options
        for (var i = 0; i < options.length; i++) {
            var option = options[i]; //current option
            var optionText = option.text; //option text ("Somalia")
            var lowerOptionText = optionText.toLowerCase(); //option text lowercased for case insensitive testing
            var lowerText = text.toLowerCase(); //searchBox value lowercased for case insensitive testing
            var regex = new RegExp("^" + text, "i"); //regExp, explained in post
            var match = optionText.match(regex); //test if regExp is true
            var contains = lowerOptionText.indexOf(lowerText) != -1; //test if searchBox value is contained by the option text
            if (match || contains) { //if one or the other goes through
                option.selected = true; //select that option
                return; //prevent other code inside this event from executing
            }
        }
    }

    
    
    gros_search_box = document.getElementById("gros-search-box");
    gros_options = document.getElementById("id_gros");
    function searchGros(){
        var text = gros_search_box.value;
        searchSelect(gros_options.options,text );  
    }


    

</script>





 


<!-- end -->

backend/app/templates/app/components/condition_select.html
<select class="form-select" id="gros_select" onchange="get()">
    {% for g in drop_gros %}
        <option selected id="{{ g.id }}">{{ g.numero}}</option>
    {% endfor %}
</select>

<select class="form-select" id="article_select">
</select>
<script>
 
function get(){
    var gros = document.getElementById("gros_select"); 
    selected_id = gros.options[gros.selectedIndex].id;
    var api = "/articles-by-gros/" + selected_id;
    var articles_select = document.getElementById("article_select");
    $.ajax({
            type: 'GET',
            url: api,
            data: {"pk": selected_id},
            success: function (response) {
                for(i=article_select.options.length-1;i>=0;i--){
                    article_select.remove(i);
                }
                response.articles.forEach(item => {
                    var option = document.createElement("option")
                    option.text = item.numero; 
                    option.id = item.id;
                    article_select.add(option);
                })
                console.log(response);
            },
            error: function (response) {
                alert(response["responseJSON"]["error"]);
            }
    });

   
}

</script>

{% comment %} function myFunction() {
  var x = document.getElementById("mySelect");
  var option = document.createElement("option");
  option.text = "Kiwi";
  option.id = "oprions_id";
  x.add(option);
}
function get_id(){
		var id = document.getElementById("mySelect");
        alert(id[id.selectedIndex].id);
} {% endcomment %}

backend/app/templates/app/components/custom_add.html
{% load static %}
{{ form.media }}  
{% load bootstrap5 %}  



<!-- First modal dialog --> 
<div class="modal fade " id="{{ model_id }}" aria-hidden="true" aria-labelledby="..." tabindex="-1">
  <div class="modal-dialog  modal-dialog-centered" id="shit">
    <div class="modal-content shadow-mg bg-light">
        <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">{{ form_title }}</h5>
        </div>
        <form  method="POST" id="{{ form_id }}">
        
        <div class="modal-body">
            
                    {% csrf_token %}
                    {% for field in form %}
                      {% if field.id_for_label == "id_soumis_tva" %}
                              <div class="form-check form-switch my-4">
                                  {{field}}
                                  <label class="form-check-label" for="{{field.id_for_label}}">{{field.label}}</label>
                              </div>  
                      {% else %}
                          <div class="form-floating mb-3">
                              {{field}}
                              <label for="{{field.id_for_label}}">{{field.label}}</label>

                          </div>
                      {% endif %}
                    {% endfor %}

        </div>
        <div class="modal-footer">
            <a  class="btn btn-light float-right mr-2"  id="close_custom_model" onclick="close_model({{ model_id }})">Annuler</a>
            <input type="submit" class="btn btn-primary float-right" id="submit_button" name="SUBMIT" onclick="close_model({{ model_id }})" value="Soumettre"></a>
        </div>

        </form>
    </div>
  </div>
</div>

<script>

function close_model(model_id) {
  var myModalEl = model_id
  var modal = bootstrap.Modal.getInstance(myModalEl)
  modal.hide();
}

</script>

backend/app/templates/app/components/custom_pagination.html
<div class="col d-flex justify-content-end">

    <nav aria-label="...">
        <ul class="pagination" id="{{ id }}">
            
        </ul>
    </nav>
</div>

backend/app/templates/app/components/delete_bulletins.html
<!-- Delete confirmation Modal -->
<div class="modal fade " id="delete_bulletins" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-md">
    <div class="modal-content">
    <div class="modal-body">
        <h6 class="mt-3">Voulez-vous supprimer l'élément actuel ?</h6>
    </div>
    
      <div class="modal-footer">
        <button type="button" class="btn btn-light shadow-none" data-bs-dismiss="modal">Annuler</button>
        <a type="link" class="btn btn-danger shadow-none" href="{% url 'delete_bulletins'  bulletins.id  %}">Je veux procéder à la suppression</a>
      </div>
    </div>
  </div>
</div>
<!-- end delete confirmation model-->

backend/app/templates/app/components/messages.html
{% if messages %}

{% for message in messages %}

<div class="alert {{ 'alert-'|add:message.extra_tags }} alert-dismissible fade show mt-3 h-25" role="alert" id="return-message" >
    {{ message }}
</div>
{% endfor %}

{% endif %} 


<script>

let return_message = document.getElementById("return-message");
return_message.addEventListener("load", removeMessage(return_message));
function removeMessage(message){
    setTimeout(function (){
            return_message.remove();
        }, 4000);
}
</script>

backend/app/templates/app/components/pagination.html
{% if data.paginator.num_pages > 1 %}
<div class="row d-none d-lg-block">
<nav aria-label="Pagenavigation">
  <ul class="pagination d-flex justify-content-end bg-gray-100  rounded py-2 ">
      {% if data.has_previous %}
        <li class="page-item mx-2">
            <a class="page-link shadow-none border-0 rounded" tabindex="-1" href="?page={{data.previous_page_number}}"><small>Précédente</small></a>
        </li>
      {% else %}
        <li class="page-item disabled mx-2">
          <a class="page-link shadow-none border-0 rounded" tabindex="-1" href=""><small>Précédente</small></a>
        </li>
      {% endif %}
      {% for i in data.paginator.page_range %}

        {% if data.number == i %}
          {% if i < 6  %}
            <li class="page-item active d-none d-md-block mx-1">
                <a class="page-link shadow-none border-0 rounded" href="?page={{i}}">{{i}}</a>
            </li>
          {% endif %}
        {% else %}
          {% if i < 6  %}
            <li class="page-item d-none d-md-block mx-1">
              <a class="page-link shadow-none border-0 rounded" href="?page={{i}}">{{i}}</a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}
     
      {% if data.paginator.num_pages > 5 %}

        {% if data.number == 1 %}
          <li class="page-item active d-md-none d-sm-block mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.number }}">{{data.number }}</a>
          </li>
        {% else %}
          <li class="page-item d-md-none d-sm-block mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page=1">1</a>
          </li>
          <li class="page-item active d-md-none d-sm-block mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.number }}">{{ data.number }}</a>
          </li>
        {% endif %}
 
        {% if data.number < data.paginator.num_pages and data.number > 5 %}
          <li class="page-item active mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{data.number }}">{{ data.number }}</a>
          </li>
        {% endif %}
        {% if data.number == data.paginator.num_pages %}
          <li class="page-item active mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.paginator.num_pages }}"> {{ data.paginator.num_pages }}</a>
          </li>        
        {% else %}
          <li class="page-item mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.paginator.num_pages }}"> {{ data.paginator.num_pages }}</a>
          </li>
        {% endif %}

      {% endif %} 



      {% if data.has_next %}
        <li class="page-item mx-2">
            <a class="page-link shadow-none border-0 rounded" href="?page={{data.next_page_number}}"><small>Suivante</small></a>
        </li>
      {% else %}
        <li class="page-item disabled mx-2">
          <a class="page-link shadow-none border-0 rounded " href=""><small>Suivante</small></a>
        </li>
      {% endif %}
  </ul>
</nav>
</div>
<div class="row d-block d-lg-none">
<nav aria-label="Page navigation ">
  <ul class="pagination d-flex justify-content-center bg-gray-100 rounded py-2 ">
      {% if data.has_previous %}
        <li class="page-item mx-2">
            <a class="page-link shadow-none border-0 rounded" tabindex="-1" href="?page={{data.previous_page_number}}"><small>Précédente</small></a>
        </li>
      {% else %}
        <li class="page-item disabled mx-2">
          <a class="page-link shadow-none border-0 rounded" tabindex="-1" href=""><small>Précédente</small></a>
        </li>
      {% endif %}
      {% for i in data.paginator.page_range %}

        {% if data.number == i %}
          {% if i < 6  %}
            <li class="page-item active d-none d-md-block mx-1">
                <a class="page-link shadow-none border-0 rounded" href="?page={{i}}">{{i}}</a>
            </li>
          {% endif %}
        {% else %}
          {% if i < 6  %}
            <li class="page-item d-none d-md-block mx-1">
              <a class="page-link shadow-none border-0 rounded" href="?page={{i}}">{{i}}</a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}
     
      {% if data.paginator.num_pages > 5 %}

        {% if data.number == 1 %}
          <li class="page-item active d-md-none d-sm-block mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.number }}">{{data.number }}</a>
          </li>
        {% else %}
          <li class="page-item d-md-none d-sm-block mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page=1">1</a>
          </li>
          <li class="page-item active d-md-none d-sm-block mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.number }}">{{data.number }}</a>
          </li>
        {% endif %}
 
        {% if data.number < data.paginator.num_pages and data.number > 5 %}
          <li class="page-item active mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{data.number }}">{{data.number }}</a>
          </li>
        {% endif %}
        {% if data.number == data.paginator.num_pages %}
          <li class="page-item active mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.paginator.num_pages }}"> {{ data.paginator.num_pages }}</a>
          </li>        
        {% else %}
          <li class="page-item mx-1">
            <a class="page-link shadow-none border-0 rounded" href="?page={{ data.paginator.num_pages }}"> {{ data.paginator.num_pages }}</a>
          </li>
        {% endif %}

      {% endif %} 



      {% if data.has_next %}
        <li class="page-item mx-2">
            <a class="page-link shadow-none border-0 rounded" href="?page={{data.next_page_number}}"><small>Suivante</small></a>
        </li>
      {% else %}
        <li class="page-item disabled mx-2">
          <a class="page-link shadow-none border-0 rounded " href=""><small>Suivante</small></a>
        </li>
      {% endif %}
  </ul>
</nav>
<div>

{% endif %}

backend/app/templates/app/components/saisie_manuelle_pagination.html
{% if data.has_other_pages %}
<nav aria-label="Page navigation example shadow-none">
  <ul class="pagination justify-content-end">
   <li class="page-item ">
      <a class="page-link shadow-none rounded-0" href="?page=all"  tabindex="-1">Afficher touts les {{ data.paginator.num_pages }} pages</a>
    </li>
    {% if data.has_previous %}
    <li class="page-item ">
      <a class="page-link shadow-none rounded-0" href="?page={{data.previous_page_number}}" tabindex="-1">Précédente</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <a class="page-link shadow-none rounded-0" href="" tabindex="-1">Précédente</a>
    </li>
    {% endif %}

    {% for i in data.paginator.page_range %}
      {% if data.number == i %}
        {% if i < 6 %}
            <li class="page-item active shadow-none"><a class="page-link shadow-none" href="?page={{i}}">{{i}}</a></li>
        {% endif %}
        {% else %}
        {% if i < 6 %}
          <li class="page-item shadow-none"><a class="page-link shadow-none" href="?page={{i}}">{{i}}</a></li>
        {% endif %}
    
      {% endif %}
    {% endfor %}

    {% if data.has_next %}
    <li class="page-item">
      <a class="page-link shadow-none rounded-0" href="?page={{data.next_page_number}}">Suivante</a>
    </li>
    {% else %}
    <li class="page-item disabled rounded-0">
      <a class="page-link shadow-none" href="">Suivante</a>
    </li>
    {% endif %}
    {% if data.paginator.num_pages > 6  %}
        <li class="page-item disabled rounded-0">
          <a class="page-link shadow-none" href="">Page actuelle {{ data.number }}</a>
        </li>  
    {% endif %}

  </ul>
</nav>
{% endif %}

backend/app/templates/app/components/search.html
{% load static %}

<form method="GET">
		<div class="row mb-2">
			<div class="col-9">
				{% csrf_token %}		
                <input type="text" class="form-control shadow-none" placeholder="Searchr..."  name="search" value="{{ request.GET.search }}" aria-describedby="basic-addon1">
			</div>

			<div class="col-3">
				<button type="submit" class="btn btn-primary w-100 shadow-none">
					<img class="image image-small"  src="{% static 'img/search.svg' %}">
				</button>
			</div>
		</div>
</form>