backend/app/urls.py
from rest_framework import routers
from django.urls import path, include

from .views.views import *
app_name='app'


router = routers.DefaultRouter()


urlpatterns = []


router.register(r'gros', GrosViewSet, basename='gros')
router.register(r'article', ArticleViewSet, basename='article')
router.register(r'position', PositionViewSet, basename='position')
router.register(r'bulletinsescort', BulletinsEscortViewSet, basename='bulletinsescort')
router.register(r'tc', TcViewSet, basename='tc')
router.register(r'sousarticle', SousArticleViewSet, basename='sousarticle')
router.register(r'visite', VisiteViewSet, basename='visite')
router.register(r'visiteitem', VisiteItemViewSet, basename='visiteitem')
router.register(r'scelle', ScelleViewSet, basename='scelle')
urlpatterns += router.urls

backend/billing/urls.py
from rest_framework import routers
from django.urls import path, include
from .views import *
app_name='billing'


router = routers.DefaultRouter()


urlpatterns = []


router.register(r'proforma', ProformaViewSet, basename='proforma')
router.register(r'groupe', GroupeViewSet, basename='groupe')
router.register(r'groupeligne', GroupeLigneViewSet, basename='groupeligne')
router.register(r'ligneprestation', LignePrestationViewSet, basename='ligneprestation')
router.register(r'ligneprestationarticle', LignePrestationArticleViewSet, basename='ligneprestationarticle')
router.register(r'boncommande', BonCommandeViewSet, basename='boncommande')
router.register(r'commande', CommandeViewSet, basename='commande')
router.register(r'facture', FactureViewSet, basename='facture')
router.register(r'paiement', PaiementViewSet, basename='paiement')
router.register(r'facturecomplementaire', FactureComplementaireViewSet, basename='facturecomplementaire')
router.register(r'lignefacturecomplementaire', LigneFactureComplementaireViewSet, basename='lignefacturecomplementaire')
router.register(r'paiementfacturecomplementaire', PaiementFactureComplementaireViewSet, basename='paiementfacturecomplementaire')
router.register(r'factureavoire', FactureAvoireViewSet, basename='factureavoire')
router.register(r'lignefactureavoire', LigneFactureAvoireViewSet, basename='lignefactureavoire')
router.register(r'bonsortie', BonSortieViewSet, basename='bonsortie')
router.register(r'bonsortieitem', BonSortieItemViewSet, basename='bonsortieitem')
router.register(r'facturelibre', FactureLibreViewSet, basename='facturelibre')
router.register(r'lignefacturelibre', LigneFactureLibreViewSet, basename='lignefacturelibre')
router.register(r'paiementfacturelibre', PaiementFactureLibreViewSet, basename='paiementfacturelibre')
router.register(r'proformagroupage', ProformaGroupageViewSet, basename='proformagroupage')
router.register(r'ligneproformagroupage', LigneProformaGroupageViewSet, basename='ligneproformagroupage')
router.register(r'facturegroupage', FactureGroupageViewSet, basename='facturegroupage')
router.register(r'paiementgroupage', PaiementGroupageViewSet, basename='paiementgroupage')
router.register(r'bonsortiegroupage', BonSortieGroupageViewSet, basename='bonsortiegroupage')
urlpatterns += router.urls

backend/src/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views.views import *
from billing.views import * 
from groupage.views import * 
import debug_toolbar

urlpatterns = [
    path('__debug__/', include(debug_toolbar.urls)),
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('api/auth/', include('authentication.urls')),
    path('api/container/', include('app.urls')),
    path('api/bareme/', include('bareme.urls')),
    path('api/billing/', include('billing.urls')),
    path('api/reposrting/', include('reporting.urls')),
    path('api/reference/', include('reference.urls')),
    path('api/groupage/', include('groupage.urls'))
]

backend/billing/models.py
from logging import raiseExceptions
from multiprocessing.spawn import prepare
from xmlrpc.client import boolean
from django.contrib.admin.sites import DefaultAdminSite
from django.db import connections, models
from datetime import date, datetime
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.core.exceptions import ValidationError
from django.db.models.deletion import CASCADE
from django.db.models.expressions import OrderBy
from django.db.models.fields import DecimalField
from django.db.models.fields.related import ForeignKey
from django.db.models.fields.reverse_related import ForeignObjectRel
from django.forms import BooleanField 
from simple_history.models import HistoricalRecords
import re
from reference.models import Client 
from django.db.models import Max, Sum
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from src.methods import *
from bareme.models import *
import app.models 
from decimal import Decimal
from groupage.models import *

def total_paiements(first_date, last_date): 


    paiamants = Paiement.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']

    paiamants_complementaire = PaiementFactureComplementaire.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']

    paiements_libre = PaiementFactureLibre.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']
    
    paiements_groupage = PaiementGroupage.objects.filter(date__range=[first_date,last_date]).aggregate(Sum('montant'))['montant__sum']

    if paiamants is None: 
        paiamants = 0 

    if paiamants_complementaire is None: 
        paiamants_complementaire = 0 

    if paiements_libre is None: 
        paiements_libre = 0

    if paiements_groupage is None: 
        paiements_groupage = 0
        
    return round(paiamants + paiamants_complementaire + paiements_libre+paiements_groupage,0)
    

        
def getNextNumber(prefix,model):
    all = model.objects.filter(date_creation__year = date.today().year).order_by("numero")
    last = all.last()

    if not last or (last.date_creation.year != date.today().year):
        return prefix+'000001'
    else: 
        max = 0
        for record in all: 
            if int(record.numero.split(prefix)[-1]) > max : 
                max = int(record.numero.split(prefix)[-1]) 

        new_int = max + 1
        new_no = prefix + format(new_int, '06d')

    return new_no 


def getNumeroProforma():
    all = Proforma.objects.filter(date_creation__year = date.today().year).order_by("id")
    last = all.last()

    if not last or (last.date_creation.year != date.today().year):
        return 'ALG000001'
    else: 
        max = 0
        for record in all: 
            if int(record.numero.split('ALG')[-1].split('FP')[-1]) > max : 
                max = int(record.numero.split('ALG')[-1].split('FP')[-1]) 

        new_int = max + 1
        new_no = 'ALG' + format(new_int, '06d')

    return new_no 

def getNumeroFacture():
    return getNextNumber('ALG',Facture)

def getNumeroBonCommande():
    return getNextNumber('BC',BonCommande)

def getNumeroBonSortie():
    return getNextNumber('BS',BonSortie)


def getNumeroBonSortieGroupage():
    return getNextNumber('BS/G/',BonSortieGroupage)

def getNumeroFactureLibre(): 
    return getNextNumber('ALG/LIBRE',FactureLibre)

def getNumeroFactureGroupage():
    return getNextNumber('GRP',FactureGroupage)

def getNumeroProformaGroupage():
    return getNextNumber('P/GRP',ProformaGroupage)


class Proforma(models.Model):
    numero = models.CharField(max_length=9,default=getNumeroProforma)
    date_creation = models.DateField(auto_now_add=True)
    gros = models.ForeignKey("app.Gros", on_delete=models.CASCADE)
    article = models.ForeignKey("app.Article", on_delete=models.CASCADE)
    date_proforma = models.DateField(auto_now=False, auto_now_add=False)
    HT = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TVA = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TTC = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    tva = models.BooleanField(default=True, verbose_name="TVA") 
    debeur = models.BooleanField(default=False, verbose_name="DEBEUR")
    DEBEUR = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    remise = models.BooleanField(default=False)
    REMISE = models.DecimalField(max_digits=15, decimal_places=2,default=0,blank=True, null=True)
    TR = models.DecimalField(max_digits=15, decimal_places=2,blank=True, null=True)
    valide = models.BooleanField(default=False, blank=True, null=True)
    trashed = models.BooleanField(default=False, blank=True, null=True)
    entreposage = models.BooleanField(default=True, blank=True, null=True)
    
    history = HistoricalRecords()  

    def validate(self):
        self.valide = True 
        self.save()
        self.set_containers_as_billed()

    class Meta:
        ordering = ["-id"]
        verbose_name_plural = "proformas"

    def set_containers_as_billed(self): 
        for line in self.get_groupes_lines(): 
            line.tc.set_as_billed()

    def is_container_loaded(self,tc): 
        self.get_groupes_lines().filter(tc=tc).exists()

    # get all the containers that are not billed & not loaded to any proforma yet
    def get_not_loaded_containers(self): 
        return app.models.Tc.objects.filter(pk__in = [tc.id for tc in self.article.get_receved_containers().filter(billed = False) if not self.is_container_loaded(tc)])
 
    @property 
    def total_number_of_containers(self): 
        return self.groupe_set.all().aggregate(Sum('tcs'))['tcs__sum'] 

    def get_groups(self): 
        return self.groupe_set.all()

    def get_groupes_lines(self):     
        return GroupeLigne.objects.filter(groupe__in = self.get_groups())

    def get_prestations(self): 
        return self.ligneprestation_set.all()

    def get_prestations_article(self): 
        return self.ligneprestationarticle_set.all()

    def get_enterposage(self):
        return self.groupe_set.all().aggregate(Sum('enterposage'))['enterposage__sum']

    def get_ttc_in_letters(self): 
        return decimalToText(self.TTC)

    def __str__(self):
        return self.numero + " / " + str(self.date_creation.year)  

    def clean(self):
        if self.id is None :
            records_count = Proforma.objects.filter(date_creation__year = date.today().year,numero = self.numero).count()
            if records_count > 0: 
                raise ValidationError({"numero":"Proforma aleady exist."})

    def calculate_totals(self): 
        total_hors_taxes = 0   
        total_hors_taxes = get_sum_hors_taxes(self.get_prestations())
        total_hors_taxes += get_sum_hors_taxes(self.get_prestations_article())    
        remise = 0     
        if self.remise: 
            total_hors_taxes,remise = calculate_remise(total_hors_taxes, self.REMISE)
        

        if self.tva: 
            total_tva = calculate_tva(total_hors_taxes) 
        else: 
            total_tva =  0  

        self.HT  = total_hors_taxes
        self.TVA  = total_tva 
        self.TR = remise
        self.TTC = total_hors_taxes + total_tva
        if self.debeur: 
            self.TTC += self.DEBEUR
        self.save()

class Groupe(models.Model): 
    proforma = models.ForeignKey("billing.Proforma",on_delete=models.CASCADE)
    type = models.ForeignKey("reference.Type", verbose_name="Container type", on_delete=models.SET_NULL,null=True)
    dangereux = models.BooleanField()
    frigo = models.BooleanField()
    tcs = models.IntegerField(null=True, blank=True)
    enterposage = models.IntegerField(null=True, blank=True)

    @property 
    def lines(self): 
        return self.groupeligne_set.all()


    class Meta:
        verbose_name_plural = "groupes"

    def __str__(self):
        return str(self.proforma) +" | "+ str(self.type) +" | " + str(self.dangereux) +" | " + str(self.frigo) 
    
class GroupeLigne(models.Model): 
    groupe = models.ForeignKey("billing.Groupe", on_delete=models.CASCADE)
    tc = models.ForeignKey("app.Tc",on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "lignes groupe"

    def __str__(self):
        return self.groupe.type.designation+" "+self.tc.tc
    
class LignePrestation(models.Model): 
    proforma = models.ForeignKey("billing.Proforma",on_delete=models.CASCADE) 
    groupe = models.ForeignKey("billing.Groupe", on_delete=models.CASCADE, null=True, blank=True)
    rubrique = models.CharField(max_length=100)
    rubrique_object = models.ForeignKey("bareme.Rubrique", related_name="rubrique_prestation", on_delete=models.PROTECT, null=True, blank=True)
    tcs = models.IntegerField()
    quantite = models.IntegerField(blank=True , null= True)
    tarif = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    HT = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TVA = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    TTC = models.DecimalField(max_digits=15, decimal_places=2,null=True, blank=True)
    code_comptable = models.CharField(max_length=30, null=True, blank=True) 
   
    def update_tva_zero(self): 
        self.TVA = 0 
        self.TTC = self.HT 
        self.save()
        
    class Meta:
        verbose_name_plural = "lignes prestation"

    def save(self, *args, **kwargs):
        if self.proforma.tva: 
            self.HT = self.tarif * self.quantite
            self.TVA = (self.HT * 19) / 100
            self.TTC = self.HT + self.TVA
        else: 
            self.HT = self.tarif * self.quantite
            self.TVA = 0
            self.TTC = self.tarif * self.quantite       
                
        super(LignePrestation, self).save(*args, **kwargs)   

    def __str__(self):

backend/billing/templates/billing/pages/affictationBareme.html
{% extends 'app/components/base.html' %}

{% block content %}


<section class="row">
    <!-- The table column -->

        <div class="card" style="min-height: 94vh;">
             <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <h4 class="card-title">Affictation bareme</h4>
                    </div>
                    <div class="col-6">
                       <div class="row">
                            <div class="col">
                                <form method="POST" id="form-affictation">
                                {% csrf_token %}
                                <div class="form-floating mb-3">
                                    <select class="form-select mb-3 shadow-none" aria-label="Default select example" id="select-gros" name="gros" >
                                        {% for item in gros %}
                                            <option id="{{ item.id }}">{{ item }}</option> 
                                        {% endfor %}
                                    </select>                     
                                    <label for="gros" >Gros</label>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-floating mb-3">
                                    <select class="form-select mb-3 shadow-none" aria-label="Default select example" id="select-bareme" name="bareme" >  
                                        {% for item in baremes %}
                                            <option id="{{ item.id }}">{{ item }}</option> 
                                        {% endfor %}
                                    </select>     
                                    </select>
                                    <label for="article" >Bareme</label>
                                </div>
                            </div>
                            <div class="col">
                                 <button type="submit" class="btn btn-primary w-100 py-3">Afficter</button>
                            </div>  
                            </form>                                                      
                       </div>

                    </div>
                </div>

                 {% include 'billing/components/affictation_bareme_table.html' %}
            </div>
            

        


    {% comment %} <div class="col-12 col-lg-3">
        <div class="card">
            <div class="card-body"> 
            <form method="POST" id="form-affictation">
            {% csrf_token %}
                <div class="form-floating mb-3">
                    <select class="form-select mb-3 shadow-none" aria-label="Default select example" id="select-gros" name="gros" >
                        {% for item in gros %}
                            <option id="{{ item.id }}">{{ item }}</option> 
                        {% endfor %}
                    </select>                     
                    <label for="gros" >Gros</label>
                </div>

                <div class="form-floating mb-3">
                    <select class="form-select mb-3 shadow-none" aria-label="Default select example" id="select-bareme" name="bareme" >  
                        {% for item in baremes %}
                            <option id="{{ item.id }}">{{ item }}</option> 
                        {% endfor %}
                    </select>     
                    </select>
                    <label for="article" >Bareme</label>
                </div>
                <button type="submit" class="btn btn-outline-primary w-100">Afficter</button>
            </form>
            </div>  
        </div> {% endcomment %}

</section>


<script>
    let form = document.getElementById('form-affictation');
    form.onsubmit = createVsiste;

    function createVsiste(event){
        form = $("#form-affictation");
        // Get the selected gros 
        let gros = document.getElementById('select-gros');
        let selected_gros_id = gros.options[gros.selectedIndex].id;

        // Get the selcted bareme 
        let bareme = document.getElementById('select-bareme');
        let selected_bareme_id = bareme.options[bareme.selectedIndex].id;

        $.ajax({
                type: 'POST',
                url: "{% url 'afficter_bareme' %}" ,
                data: {
                        "selected_gros_id" : selected_gros_id,
                        "selected_bareme_id": selected_bareme_id
                    },
                headers: { "X-CSRFToken": getCookie("csrftoken") },
                success: function (response) {
                    Notification('Succès',"L'opération a été effectuée avec succès.",'success');       
                    console.log(response);
                },
                error: function (response) {
                    console.log(response);
                }
            }) 
    }

    function getCookie(c_name)
    {
        if (document.cookie.length > 0)
        {
            c_start = document.cookie.indexOf(c_name + "=");
            if (c_start != -1)
            {
                c_start = c_start + c_name.length + 1;
                c_end = document.cookie.indexOf(";", c_start);
                if (c_end == -1) c_end = document.cookie.length;
                return unescape(document.cookie.substring(c_start,c_end));
            }
        }
        return "";
    }


</script>

{% endblock content %}

backend/billing/templates/billing/pages/facture_avoire_details.html
{% extends 'app/components/base.html' %}
{% load humanize %}
{% block content %}
{% include 'app/components/navbar.html' with title=facture_avoire.facture.numero|add:"/FA"|add:facture_avoire.numero %}
{% include 'app/components/messages.html' %}


<div class="card bg-gray-200 mt-4 mt-lg-0 mb-4">
    <div class="card-body">
        <div class="row">
            <div class="col-12 col-lg-9">

                <div class="mb-2">
                    Facture &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ facture_avoire.facture }}</span>
                </div>

                <div class="mb-2">
                    Gros &nbsp; &nbsp; <span class="badge bg-primary p-2">{{ facture_avoire.facture.proforma.gros.gros }}</span>
                </div>

                <div class="mb-2">
                    Article&nbsp; &nbsp; <span class="badge bg-primary p-2">{{ facture_avoire.facture.proforma.article.numero }}</span>
                </div> 

                <div class="mb-2">
                    Client &nbsp; &nbsp;<span>{{ facture_avoire.facture.proforma.article.client }}</span>
                </div>
                <div class="mb-2">
                    Date &nbsp; &nbsp;<span class="badge bg-primary p-2">{{ facture_avoire.date_creation }}</span>
                </div>
            </div> 
            <div class="col-12 col-lg-3">
                <hr class="d-block d-lg-none">
                <div class="card bg-gray-200 mt-3">
                    <div class="card-body p-0">

                        <div class="row">
                            <div class="col-4 col-lg-4">
                            
                                <div class="mb-2">
                                    <span class="badge bg-gray-100 text-primary p-2"> HT  </span>
                                </div>
                                <div class="mb-2">
                                    <span class="badge bg-gray-100 text-primary p-2"> TVA </span>
                                </div>         

                                <div class="mb-2">
                                    <span class="badge bg-primary p-2">  TTC </span>
                                </div>
                            </div>

                            <div class="col-8 col-lg-8">
                              
                                <div class="mb-2">
                                   <span class="badge bg-gray-300 text-primary p-2" id="info_ht"> {{ facture_avoire.HT| intcomma  }} DA</span>
                                </div>
                                <div class="mb-2">
                                   <span class="badge bg-gray-300 text-primary p-2 " id="info_tva"> {{ facture_avoire.TVA | intcomma }} DA</span>
                                </div>         

                                <div class="mb-2">
                                    <span class="badge bg-primary p-2" id="info_ttc"> {{ facture_avoire.TTC| intcomma  }} DA</span>
                                </div>
                            </div>
                          
                       
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>
</div>



    <div class="row row-cols-auto">
        <div class="col">
            <div class="card mb-3">
                <div class="card-body p-2">
                    <div class="row">
                        <div class="col-12">
    
                                <a href={% url 'print_facture_avoire' facture_avoire.id%} target="_blank" class="btn btn-secondary shadow-none" tabindex="-1" role="button" aria-disabled="true" >
                                    <svg xmlns="http://www.w3.org/2000/svg" id="Filled" viewBox="0 0 24 24" width="16" height="16"><path d="M19,4a4,4,0,0,0-4-4H9A4,4,0,0,0,5,4V5H19Z"/><rect x="5" y="15" width="14" height="9" rx="3"/><path d="M19,7H5a5.006,5.006,0,0,0-5,5v4a5,5,0,0,0,3,4.576V18a5.006,5.006,0,0,1,5-5h8a5.006,5.006,0,0,1,5,5v2.576A5,5,0,0,0,24,16V12A5.006,5.006,0,0,0,19,7Zm-1,4H16a1,1,0,0,1,0-2h2a1,1,0,0,1,0,2Z"/></svg>
                                </a>     
                                {% if not facture_complementaire.paid %}
                                <a type="link" class="btn btn-primary shadow-none" data-bs-toggle="modal" href="#add_prestation_model" data-bs-toggle="tooltip" data-bs-placement="top">
                                    + Préstation
                                </a>                          
                                {% endif %}    
    
    
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="card mb-3">
        <div class="card-body p-2 p-lg-3">
            <span class="badge bg-gray-100 text-primary p-2 mb-3"> Préstations </span>
    
            <div class="table-responsive table-hover mb-3">
                <table class="table table-hover table-borderless table-centered table-nowrap mb-0 rounded">
                    <thead class="thead-light border-0">
                        <tr>
                            <th class="rounded-start">Rubrique </th>
                            <th scope="col">Tarif</th>
                            <th scope="col">Quantité</th>
                            <th scope="col">HT</th>
                            <th scope="col">TVA</th>
                            <th class="rounded-end">TTC</th>
                        </tr>
                    </thead>
                    <tbody id="prstation_table">
                        {% for ligne in lignes %}
    
                                <tr >
                                    <td class="rounded-start"> {{ ligne.rubrique }}  </td>
                                    <td> {{ ligne.tarif }} </td>
                                    <td> {{ ligne.quantite }} </td>
                                    <td> {{ ligne.HT }} </td>
                                    <td> {{ ligne.TVA }} </td>
                                    <td class="rounded-end"> {{ ligne.TTC }} </td>
                                </tr>
    
                        {% endfor %}
    
                    </tbody>
                </table>  
            </div>
        </div>
    </div>

    <div class="modal fade"  id="add_prestation_model" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered  modal-xl modal-dialog-scrollable" >
          <div class="modal-content shadow-lg" >
              <div class="modal-body">
                  <span class="badge bg-gray-100 text-primary p-2 mb-3"> Paiemenet</span>
               
                  <div class="row">
                      <div class="col-12 col-lg-4 mb-3 mb-lg-0">
                          <div class="form-floating">
                              <select class="form-select shadow-none" id="rubrique" aria-label="Floating label select example">
                                  {% for rubrique in rubriques %}
                                      <option >{{ rubrique.designation }}</option>
                                  {% endfor %}
                              </select>
                              <label for="floatingSelect">Rubrique</label>
                          </div>  
                      </div>
                      <div class="col col-lg-3 mb-3 mb-lg-0">
                          <form class="form-floating shadow-none">
                              <input type="number" step="0.01" min="0" class="form-control shadow-none" id="tarif_prestation" value="1">
                              <label for="floatingInputValue">Tarif</label>
                          </form>
                      </div>
                      <div class="col col-lg-2">
                          <form class="form-floating shadow-none">
                              <input type="number"  min="0" class="form-control shadow-none" id="quantite_prestation" value="1">
                              <label for="floatingInputValue">Quantité</label>
                          </form>
                      </div>
                      <div class="col-12 col-lg-3">
                          <div class="form-floating mb-3">
                              <input type="date" name="date_proforma" class="form-control shadow-none" id="date_prestation">             
                              <label for="id_date_proforma">Date</label>
                          </div>                    
                      </div>
                      
      
                  </div>
               
          </div>
          <div class="modal-footer">
              <div class="float-end">   
                  <button class="btn btn-primary float-end shadow-none px-3" onclick="addPrestation()">Ajouter préstation</button>
                  <a class="btn btn-gray-100 float-end mx-2" data-bs-dismiss="modal">Annuler</a>     
              </div>
          </div>
        </div>
      </div>
      </div>



<script>
 
// set the date for date paiement field to today 
var now = new Date();
var day = ("0" + now.getDate()).slice(-2);
var month = ("0" + (now.getMonth() + 1)).slice(-2);
var today = now.getFullYear()+"-"+(month)+"-"+(day);



$('#date_paiement').val(today); 

// get CSRFToken from cookies 
function getCookie(c_name)
{
    if (document.cookie.length > 0)
    {
        c_start = document.cookie.indexOf(c_name + "=");
        if (c_start != -1)
        {
            c_start = c_start + c_name.length + 1;
            c_end = document.cookie.indexOf(";", c_start);
            if (c_end == -1) c_end = document.cookie.length;
            return unescape(document.cookie.substring(c_start,c_end));
        }
    }
    return "";
}



function fillPrestation(data){
       
    table = document.getElementById("prstation_table");
    while(table.hasChildNodes()){
        table.removeChild(table.firstChild);
    }

    data.forEach(item => {
        var row = table.insertRow(0);
        var rubrique_cell = row.insertCell(0);
        var tarif_cell = row.insertCell(1);
        var quantite_cell = row.insertCell(2);
        var HT_cell = row.insertCell(3);
        var TVA_cell = row.insertCell(4);
        var TTC_cell = row.insertCell(5);

        rubrique_cell.innerHTML= item.rubrique;
        tarif_cell.innerHTML= item.tarif;
        quantite_cell.innerHTML= item.quantite;
        HT_cell.innerHTML= item.HT;
        TVA_cell.innerHTML= item.TVA;
        TTC_cell.innerHTML= item.TTC;

    })

} 


// Add prestation function 
function addPrestation(){
    let rubrique = document.getElementById("rubrique").value;
    let tarif = document.getElementById("tarif_prestation").value;
    let quantite = document.getElementById("quantite_prestation").value;
    let date_prestation = document.getElementById("date_prestation").value;

    if (date_prestation == ""){
        Notification("error","S'il vous plaît assurez-vous de remplir tous les champs avant de soumettre.","danger");
    }

    $.ajax({
        type: 'POST',
        url: "{% url 'add_prestation_facture_avoire'  facture_avoire.id %}",
        data: {
            "rubrique": rubrique,
            "date_prestation": date_prestation,
            "tarif": tarif,
            "quantite": quantite,
            "date": date_prestation
        },
        dataType: 'json', 
        headers: { "X-CSRFToken": getCookie("csrftoken") },
        success: function (response) {  
            $('#add_prestation_model').modal('hide'); 
            fillPrestation(response.data);
            document.getElementById("info_ht").innerHTML = response.bill_info.HT + " DA";       
            document.getElementById("info_tva").innerHTML = response.bill_info.TVA + " DA";       
            document.getElementById("info_ttc").innerHTML = response.bill_info.TTC + " DA";  
            success();
        },
        error: function (response) {
            console.log(response);
        }
      }) 

}

</script>
{% endblock content %}